# Generated by Django 6.0.5 on 2026-05-18 15:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RouteCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("start_location", models.CharField(max_length=255)),
                ("finish_location", models.CharField(max_length=255)),
                ("response_json", models.JSONField()),
                ("hit_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "route_cache",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opis_id", models.IntegerField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(db_index=True, max_length=2)),
                ("rack_id", models.IntegerField(blank=True, null=True)),
                ("min_price", models.DecimalField(decimal_places=4, max_digits=8)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("geocoded", models.BooleanField(db_index=True, default=False)),
                ("geocoded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "fuel_stations",
                "ordering": ["min_price"],
                "indexes": [
                    models.Index(
                        fields=["state", "geocoded"],
                        name="fuel_statio_state_d61f05_idx",
                    )
                ],
            },
        ),
    ]
